#!/bin/bash
# prepare-llm.sh
# Exports key Obsidian vault notes as a single context file for Claude / LLMs.
# Run from the repo root: bash scripts/prepare-llm.sh
# Output: .claude/sessions/vault-context.md  (≤4000 tokens)

VAULT="${VAULT_PATH:-graphify-out/obsidian}"
IMPORT_DROP="${IMPORT_DROP:-graphify-out/obsidian/_imports}"
OUT=".claude/sessions/vault-context.md"
MAX_WORDS="${MAX_WORDS:-3000}"

mkdir -p ".claude/sessions"

# Auto-import any non-Markdown files dropped in _imports/
if [ -d "$IMPORT_DROP" ] && command -v python3 >/dev/null 2>&1; then
  shopt -s nullglob
  for f in "$IMPORT_DROP"/*.{pdf,docx,pptx,xlsx,xls,html,csv,json,xml}; do
    echo "📥 Auto-importing: $f" >&2
    python3 scripts/vault-import.py "$f" --vault "$VAULT" --folder "_markitdown" --tag markitdown/auto 2>&1 >&2 && rm "$f"
  done
  shopt -u nullglob
fi

# Priority notes to always include
PRIORITY=(
  "HOME.md"
  "Index.md"
  "UFCD_intro.md"
  "Security by Design.md"
)

# Pattern notes (security concepts + defenses)
CONCEPTS=(
  "SQL Injection.md"
  "Cross-Site Scripting (XSS).md"
  "Cross-Site Request Forgery (CSRF).md"
  "Brute Force Attacks and Account Lockout.md"
  "Session Hijacking and Authentication.md"
  "Prepared Statements (SQL Injection Defense).md"
  "Output Encoding and Input Validation (XSS Defense).md"
  "Anti-CSRF Tokens.md"
  "Rate Limiting and Account Lockout (Brute Force Defense).md"
  "Secure Cookies and HTTPS (Session Defense).md"
)

echo "# Vault Context — $(date +%Y-%m-%d)" > "$OUT"
echo "" >> "$OUT"
echo "> Auto-generated by scripts/prepare-llm.sh. Do not edit manually." >> "$OUT"
echo "" >> "$OUT"

total_words=0

add_note() {
  local file="$1"
  local label="$2"
  local path="$VAULT/$file"

  [ -f "$path" ] || return

  local words
  words=$(wc -w < "$path" 2>/dev/null || echo 0)

  if [ $((total_words + words)) -gt "$MAX_WORDS" ]; then
    echo "⚠️  Skipping $file (budget exhausted)" >&2
    return
  fi

  echo "## $label" >> "$OUT"
  echo "" >> "$OUT"
  # Strip YAML frontmatter
  python3 -c "
import sys
content = open('$path').read()
if content.startswith('---'):
    end = content.find('---', 3)
    if end != -1:
        content = content[end+3:].lstrip()
print(content.rstrip())
" >> "$OUT"
  echo "" >> "$OUT"
  echo "---" >> "$OUT"
  echo "" >> "$OUT"
  total_words=$((total_words + words))
}

for note in "${PRIORITY[@]}"; do
  add_note "$note" "${note%.md}"
done

for note in "${CONCEPTS[@]}"; do
  add_note "$note" "${note%.md}"
done

wc_out=$(wc -w < "$OUT")
echo "✅ Vault context: $OUT  (~$wc_out words / ~$((wc_out * 13 / 10)) tokens)" >&2
